name: my work
on: [push, workflow_dispatch]

jobs:
  run-crd:
    runs-on: windows-latest
    steps:
      - name: download library
        shell: powershell
        run: |
          pip install playwright
          playwright install chromium

      - name: create file 
        shell: powershell
        run: |
          
          

      - name: Ket noi voi tai khoan Google
        shell: powershell
        env:
          CMD_CODE: ${{ secrets.POWERSHELL_CODE_REMOTEDESKTOP }}
          PIN: ${{ secrets.PIN }}
        run: |
          $finalCmd = $env:CMD_CODE + " --pin=" + $env:PIN
          Invoke-Expression $finalCmd
          
      - name: Giu ket noi
        run: Start-Sleep -Seconds 2147483
